-- Initial schema for the AI Interview Preparation Platform.
--
-- Table and camelCase column names match backend/app/database.py and the existing app data.
-- Row Level Security is enabled with no policies: the public anon key (shipped to the browser)
-- cannot read or write these tables. Only the backend, using SUPABASE_SERVICE_ROLE_KEY, can.

-- ---------------------------------------------------------------------------
-- Users: profile row per signed-in Google account
-- ---------------------------------------------------------------------------
create table if not exists public."Users" (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text,
  email       text not null unique,
  picture     text
);

-- ---------------------------------------------------------------------------
-- Interviews: generated mock interviews owned by a user
-- ---------------------------------------------------------------------------
create table if not exists public."Interviews" (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz not null default now(),
  interview_id       uuid not null unique default gen_random_uuid(),
  jobposition        text not null,
  jobdescription     text,
  interviewduration  text not null default '15',
  type               text,
  "questionList"     jsonb not null default '[]'::jsonb,
  "userEmail"        text not null
);

create index if not exists interviews_user_email_idx
  on public."Interviews" ("userEmail", id desc);

-- ---------------------------------------------------------------------------
-- interview-feedback: one graded report per interview attempt
-- (the foreign key lets the API embed feedback rows when selecting interviews)
-- ---------------------------------------------------------------------------
create table if not exists public."interview-feedback" (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  interview_id    uuid not null references public."Interviews" (interview_id) on delete cascade,
  "userName"      text not null,
  "userEmail"     text not null default '',
  feedback        jsonb not null,
  recommendation  boolean not null default false
);

create index if not exists interview_feedback_interview_id_idx
  on public."interview-feedback" (interview_id);

-- ---------------------------------------------------------------------------
-- Aptitude question bank and quiz attempts
-- ---------------------------------------------------------------------------
create table if not exists public.aptitude_questions (
  id                    bigint generated by default as identity primary key,
  created_at            timestamptz not null default now(),
  category              text not null,
  topic                 text,
  difficulty            text not null check (difficulty in ('easy', 'medium', 'hard')),
  "questionText"        text not null,
  options               jsonb not null default '[]'::jsonb,
  "correctOptionIndex"  integer,
  explanation           text
);

create index if not exists aptitude_questions_category_difficulty_idx
  on public.aptitude_questions (category, difficulty);

create table if not exists public.aptitude_attempts (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz not null default now(),
  "userId"          text,
  "userEmail"       text not null,
  category          text,
  difficulty        text,
  score             integer not null check (score >= 0),
  "totalQuestions"  integer not null check ("totalQuestions" > 0),
  accuracy          integer not null check (accuracy between 0 and 100),
  "userAnswers"     jsonb not null default '[]'::jsonb,
  completed_at      timestamptz not null default now()
);

create index if not exists aptitude_attempts_user_email_idx
  on public.aptitude_attempts ("userEmail", id desc);

-- ---------------------------------------------------------------------------
-- Lock tables to the backend (service role bypasses RLS)
-- ---------------------------------------------------------------------------
alter table public."Users"              enable row level security;
alter table public."Interviews"         enable row level security;
alter table public."interview-feedback" enable row level security;
alter table public.aptitude_questions   enable row level security;
alter table public.aptitude_attempts    enable row level security;
