import { apiRequest } from "@/services/apiClient";

/**
 * Aptitude Module - question bank catalog, quiz papers, grading and attempt history.
 *
 * Questions are drawn from the seeded Supabase bank (backend/seed_aptitude.py), not
 * generated by AI. The backend keeps the answer key: a quiz paper arrives without
 * `correctOptionIndex`, and grading happens when the paper is submitted.
 */

export const DIFFICULTY_OPTIONS = [
  { value: "easy", label: "Easy" },
  { value: "medium", label: "Medium" },
  { value: "hard", label: "Hard" },
  { value: "mixed", label: "Mixed" },
];

export const QUESTION_COUNT_OPTIONS = [5, 10, 15, 20];

export const EMPTY_CATALOG = { categories: [], totalQuestions: 0, difficulties: [] };

/** Categories, topics and per-difficulty counts currently in the bank. */
export function fetchAptitudeCatalog() {
  return apiRequest("/api/aptitude/catalog");
}

/**
 * Draw a fresh randomised paper. The backend avoids questions this candidate saw in
 * recent quizzes with the same settings, so repeating a drill gives new questions.
 */
export function startAptitudeQuiz({ category, topic, difficulty, questionCount }) {
  return apiRequest("/api/aptitude/quizzes", {
    method: "POST",
    body: { category, topic, difficulty, questionCount },
  });
}

/** Re-fetch an in-progress paper with its original option order (e.g. after a refresh). */
export function fetchAptitudeQuiz(quizId) {
  return apiRequest(`/api/aptitude/quizzes/${quizId}`);
}

/**
 * Submit answers for grading.
 * @param {Array<{questionId: number, selectedIndex: number|null}>} answers
 */
export function submitAptitudeQuiz(quizId, { answers, timeTakenSeconds }) {
  return apiRequest(`/api/aptitude/quizzes/${quizId}/submit`, {
    method: "POST",
    body: { answers, timeTakenSeconds },
  });
}

export function fetchAptitudeAttempts() {
  return apiRequest("/api/aptitude/attempts");
}

/** One past attempt with its stored per-question review. */
export function fetchAptitudeAttempt(attemptId) {
  return apiRequest(`/api/aptitude/attempts/${attemptId}`);
}

/** Seconds as m:ss, for timers and "time taken" labels. */
export function formatDuration(totalSeconds) {
  const seconds = Math.max(0, Math.round(totalSeconds || 0));
  return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`;
}

export function accuracyTone(accuracy) {
  if (accuracy >= 80) return "text-emerald-600";
  if (accuracy >= 50) return "text-amber-600";
  return "text-red-600";
}
